version: '2.3'
services:
  mysql:
    image: "mysql:5.6"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: uni-hibernate
    networks:
      hibernate:
        ipv4_address: 192.164.12.2
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: hibernate-mysql-volume
        target: /var/lib/mysql
  adminer:
    image: "adminer"
    container_name: adminer
    networks:
      hibernate:
        ipv4_address: 192.164.12.3
    ports:
      - 8086:8080
networks:
  hibernate:
    driver: bridge
    ipam:
      config:
        - subnet: 192.164.12.0/24

volumes:
  hibernate-mysql-volume: